import { Either, ParseResult, Schema } from "effect";
import { isIP } from "node:net";
import { isAbsolute } from "node:path";
import { digestOf } from "../identity.ts";
import type { JsonValue } from "../../shared/types.ts";
import { dockerProfileError, type DockerProfileError } from "./errors.ts";

export const DOCKER_EXECUTION_PROFILE_SCHEMA_VERSION: 1 = 1;
export const DOCKER_PROFILE_SCHEMA_VERSION = DOCKER_EXECUTION_PROFILE_SCHEMA_VERSION;
export const DOCKER_PROFILE_NETWORK_POLICY_VERSION: 1 = 1;
export const DOCKER_PROFILE_NETWORK_DENY_CIDRS: readonly [string, ...string[]] = Object.freeze(["0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24", "192.0.2.0/24", "192.168.0.0/16", "198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24", "224.0.0.0/4", "240.0.0.0/4", "::/0"]);
const NETWORK_ALLOWED_PROTOCOLS: readonly ["dns", "https"] = Object.freeze(["dns", "https"]);
const PROFILE_CONTROLLERS: readonly ["cpu", "memory", "pids"] = Object.freeze(["cpu", "memory", "pids"]);
export type DockerExecutionProfileSecurityLevel = "managed-rootless/v1" | "managed-vm-rootless/v1";
export interface DockerProfileUnixEndpoint { readonly path: string; readonly peerUid: number }
export interface DockerProfileNetworkPolicy { readonly version: 1; readonly dns: { readonly mode: "explicit"; readonly servers: readonly [string, ...string[]] }; readonly egress: { readonly mode: "rootless-nat"; readonly allowedProtocols: readonly ["dns", "https"]; readonly denyPrivateNetworks: true; readonly denySiblingSyntheticEndpoints: true; readonly denyCidrs: readonly [string, ...string[]]; readonly ipv6: "disabled"; readonly disableHostLoopback: true; readonly portDriver: "none"; readonly daemonBridge: "none"; readonly exclusiveNetwork: true; readonly icc: false } }
export interface DockerExecutionProfileV1 {
  readonly schemaVersion: 1; readonly profileId: string; readonly securityLevel: DockerExecutionProfileSecurityLevel; readonly semanticPolicyRevision: string;
  readonly transport: { readonly kind: "unix"; readonly hostMachineIdentity: string; readonly dockerSocket: DockerProfileUnixEndpoint; readonly controlSocket: DockerProfileUnixEndpoint & { readonly protocol: "niceeval-docker-profile-control/v1" } };
  readonly backend: { readonly kind: "local-systemd" | "dedicated-linux-vm"; readonly machineIdentity: string; readonly owner: { readonly uid: number; readonly gid: number }; readonly filesystem: { readonly identity: string; readonly mountPath: string; readonly dockerRootDir: string; readonly limitBytes: number }; readonly cgroup: { readonly aggregatePath: string; readonly policyRevision: string; readonly controllers: readonly ["cpu", "memory", "pids"] } };
  readonly capacity: { readonly cpus: number; readonly memoryBytes: number; readonly memorySwapBytes: 0; readonly pids: number; readonly maxContainers: number; readonly maxBuilds: number; readonly aggregate: { readonly cpus: number; readonly memoryBytes: number; readonly memorySwapBytes: 0; readonly pids: number } };
  readonly policy: { readonly hostLoopback: false; readonly tcpDockerEndpoint: false; readonly outerSocketInjection: false; readonly privilegedTranslation: "rootless-userns"; readonly writableRoot: "declared-tmpfs-only"; readonly network: DockerProfileNetworkPolicy };
}
export type DockerExecutionProfileV1Draft = Omit<DockerExecutionProfileV1, "semanticPolicyRevision">;
export interface DockerProfilePublicSummary { readonly schemaVersion: 1; readonly profileId: string; readonly securityLevel: DockerExecutionProfileSecurityLevel; readonly semanticPolicyRevision: string; readonly capacity: DockerExecutionProfileV1["capacity"] }
type DockerExecutionProfileSemanticInput = Pick<DockerExecutionProfileV1, "securityLevel" | "backend" | "policy">;

const ParseOptions = Object.freeze({ errors: "all" as const, exact: true, onExcessProperty: "error" as const });
type PlainObject = Readonly<Record<PropertyKey, unknown>>;
const PlainObjectSchema = Schema.declare<PlainObject>((value): value is PlainObject => typeof value === "object" && value !== null && !Array.isArray(value) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null), { identifier: "DockerProfilePlainObject", description: "a plain object or null-prototype record" });
const plainStruct = <Fields extends Schema.Struct.Fields>(fields: Fields) => Schema.compose(Schema.Struct(fields), { strict: false })(PlainObjectSchema);
const string = (id: string) => Schema.String.pipe(Schema.filter((value) => value.trim() !== "" && !value.includes("\0"), { identifier: id, description: "a non-empty string without NUL" }));
const path = (id: string) => string(id).pipe(Schema.filter(isAbsolute, { identifier: id, description: "an absolute path" }));
const nonNegative = (id: string) => Schema.JsonNumber.pipe(Schema.filter((value) => Number.isSafeInteger(value) && value >= 0, { identifier: id, description: "a non-negative safe integer" }));
const positiveInteger = (id: string) => Schema.JsonNumber.pipe(Schema.filter((value) => Number.isSafeInteger(value) && value > 0, { identifier: id, description: "a positive safe integer" }));
const positiveFinite = (id: string) => Schema.JsonNumber.pipe(Schema.filter((value) => Number.isFinite(value) && value > 0, { identifier: id, description: "a positive finite number" }));
function isPublicDnsServer(value: string): boolean {
  const kind = isIP(value);
  if (kind === 4) { const [a, b, c] = value.split(".").map(Number); if (a === undefined || b === undefined || c === undefined) return false; if (a === 0 || a === 10 || a === 127 || a >= 224) return false; if (a === 100 && b >= 64 && b <= 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168) return false; if (a === 192 && b === 0 && (c === 0 || c === 2) || a === 198 && (b === 18 || b === 19 || b === 51 && c === 100) || a === 203 && b === 0 && c === 113) return false; return true; }
  if (kind !== 6) return false; const v = value.toLowerCase(); if (v.startsWith("::ffff:")) return isPublicDnsServer(v.slice(7)); return v !== "::" && v !== "::1" && !v.startsWith("fc") && !v.startsWith("fd") && !v.startsWith("fe8") && !v.startsWith("fe9") && !v.startsWith("fea") && !v.startsWith("feb") && !v.startsWith("ff") && !v.startsWith("2001:db8:");
}
const DnsServerSchema = string("DockerProfilePublicDnsServer").pipe(Schema.filter(isPublicDnsServer, { identifier: "DockerProfilePublicDnsServer", description: "a public IP address, not a private or synthetic endpoint" }));
const CidrsSchema = Schema.NonEmptyArray(Schema.String).pipe(Schema.filter((v) => v.length === DOCKER_PROFILE_NETWORK_DENY_CIDRS.length && v.every((x, i) => x === DOCKER_PROFILE_NETWORK_DENY_CIDRS[i]), { identifier: "DockerProfileDenyCidrs", description: "the v1 fail-closed CIDR set" }));
const EndpointSchema = plainStruct({ path: path("DockerProfileSocketPath"), peerUid: nonNegative("DockerProfilePeerUid") });
const NetworkSchema = plainStruct({
  version: Schema.Literal(1),
  dns: plainStruct({ mode: Schema.Literal("explicit"), servers: Schema.NonEmptyArray(DnsServerSchema) }),
  egress: plainStruct({ mode: Schema.Literal("rootless-nat"), allowedProtocols: Schema.Tuple(Schema.Literal("dns"), Schema.Literal("https")), denyPrivateNetworks: Schema.Literal(true), denySiblingSyntheticEndpoints: Schema.Literal(true), denyCidrs: CidrsSchema, ipv6: Schema.Literal("disabled"), disableHostLoopback: Schema.Literal(true), portDriver: Schema.Literal("none"), daemonBridge: Schema.Literal("none"), exclusiveNetwork: Schema.Literal(true), icc: Schema.Literal(false) }),
});
const CapacitySchema = plainStruct({ cpus: positiveFinite("DockerProfileCapacityCpus"), memoryBytes: positiveInteger("DockerProfileCapacityMemoryBytes"), memorySwapBytes: Schema.Literal(0), pids: positiveInteger("DockerProfileCapacityPids"), maxContainers: positiveInteger("DockerProfileCapacityMaxContainers"), maxBuilds: positiveInteger("DockerProfileCapacityMaxBuilds"), aggregate: plainStruct({ cpus: positiveFinite("DockerProfileAggregateCpus"), memoryBytes: positiveInteger("DockerProfileAggregateMemoryBytes"), memorySwapBytes: Schema.Literal(0), pids: positiveInteger("DockerProfileAggregatePids") }) }).pipe(Schema.filter((v) => v.aggregate.cpus >= v.cpus && v.aggregate.memoryBytes >= v.memoryBytes && v.aggregate.pids >= v.pids, { identifier: "DockerProfileCapacity", description: "aggregate capacity at least as large as allocatable CPU, memory and PID capacity" }));

/** The full descriptor wire format; closed objects are exact Structs and reject class instances. */
export const DockerExecutionProfileV1Schema: Schema.Schema<DockerExecutionProfileV1, PlainObject> = plainStruct({
  schemaVersion: Schema.Literal(1), profileId: string("DockerProfileId"), securityLevel: Schema.Literal("managed-rootless/v1", "managed-vm-rootless/v1"), semanticPolicyRevision: string("DockerProfileSemanticPolicyRevision"),
  transport: plainStruct({ kind: Schema.Literal("unix"), hostMachineIdentity: string("DockerProfileHostMachineIdentity"), dockerSocket: EndpointSchema, controlSocket: plainStruct({ path: path("DockerProfileControlSocketPath"), peerUid: nonNegative("DockerProfileControlPeerUid"), protocol: Schema.Literal("niceeval-docker-profile-control/v1") }) }),
  backend: plainStruct({ kind: Schema.Literal("local-systemd", "dedicated-linux-vm"), machineIdentity: string("DockerProfileBackendMachineIdentity"), owner: plainStruct({ uid: nonNegative("DockerProfileOwnerUid"), gid: nonNegative("DockerProfileOwnerGid") }), filesystem: plainStruct({ identity: string("DockerProfileFilesystemIdentity"), mountPath: path("DockerProfileMountPath"), dockerRootDir: path("DockerProfileDockerRootDir"), limitBytes: positiveInteger("DockerProfileFilesystemLimitBytes") }), cgroup: plainStruct({ aggregatePath: path("DockerProfileAggregatePath"), policyRevision: string("DockerProfileCgroupPolicyRevision"), controllers: Schema.Tuple(Schema.Literal("cpu"), Schema.Literal("memory"), Schema.Literal("pids")) }) }),
  capacity: CapacitySchema,
  policy: plainStruct({ hostLoopback: Schema.Literal(false), tcpDockerEndpoint: Schema.Literal(false), outerSocketInjection: Schema.Literal(false), privilegedTranslation: Schema.Literal("rootless-userns"), writableRoot: Schema.Literal("declared-tmpfs-only"), network: NetworkSchema }),
});
export const DockerExecutionProfileSchema = DockerExecutionProfileV1Schema;
function nonEmpty(values: readonly string[]): readonly [string, ...string[]] { const [first, ...rest] = values; if (first === undefined) throw new Error("expected non-empty tuple"); return Object.freeze([first, ...rest]); }
function freezeProfile(profile: DockerExecutionProfileV1): DockerExecutionProfileV1 { return Object.freeze({ ...profile, transport: Object.freeze({ ...profile.transport, dockerSocket: Object.freeze({ ...profile.transport.dockerSocket }), controlSocket: Object.freeze({ ...profile.transport.controlSocket }) }), backend: Object.freeze({ ...profile.backend, owner: Object.freeze({ ...profile.backend.owner }), filesystem: Object.freeze({ ...profile.backend.filesystem }), cgroup: Object.freeze({ ...profile.backend.cgroup, controllers: PROFILE_CONTROLLERS }) }), capacity: Object.freeze({ ...profile.capacity, memorySwapBytes: 0, aggregate: Object.freeze({ ...profile.capacity.aggregate, memorySwapBytes: 0 }) }), policy: Object.freeze({ ...profile.policy, network: Object.freeze({ ...profile.policy.network, dns: Object.freeze({ ...profile.policy.network.dns, servers: nonEmpty(profile.policy.network.dns.servers) }), egress: Object.freeze({ ...profile.policy.network.egress, allowedProtocols: NETWORK_ALLOWED_PROTOCOLS, denyCidrs: DOCKER_PROFILE_NETWORK_DENY_CIDRS }) }) }) }); }
function semanticPolicyJson(input: DockerExecutionProfileSemanticInput): JsonValue { return { schemaVersion: 1, securityLevel: input.securityLevel, backend: { kind: input.backend.kind, cgroup: { policyRevision: input.backend.cgroup.policyRevision, controllers: [...input.backend.cgroup.controllers] } }, policy: { hostLoopback: input.policy.hostLoopback, tcpDockerEndpoint: input.policy.tcpDockerEndpoint, outerSocketInjection: input.policy.outerSocketInjection, privilegedTranslation: input.policy.privilegedTranslation, writableRoot: input.policy.writableRoot, network: { version: input.policy.network.version, dns: { mode: input.policy.network.dns.mode, servers: [...input.policy.network.dns.servers] }, egress: { ...input.policy.network.egress, allowedProtocols: [...input.policy.network.egress.allowedProtocols], denyCidrs: [...input.policy.network.egress.denyCidrs] } } } }; }
export function dockerExecutionProfileSemanticPolicyRevisionOf(input: DockerExecutionProfileSemanticInput): string { return digestOf(semanticPolicyJson(input)).slice(0, 8); }
export const dockerProfileSemanticPolicyRevisionOf = dockerExecutionProfileSemanticPolicyRevisionOf;
function schemaError(value: unknown, error: ParseResult.ParseError): DockerProfileError { const issue = ParseResult.ArrayFormatter.formatErrorSync(error)[0]; const suffix = issue?.path.map(String).join("."); const errorPath = `profile${suffix === undefined || suffix === "" ? "" : `.${suffix}`}`; const root = typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined; if (errorPath === "profile.schemaVersion") return dockerProfileError({ code: "sandbox.docker-profile-unknown-version", path: errorPath, message: `Unsupported Docker execution profile schema version ${JSON.stringify(root?.schemaVersion)}; expected 1` }); if (errorPath === "profile.securityLevel") return dockerProfileError({ code: "sandbox.docker-profile-security-level-unsupported", path: errorPath, message: `Unsupported Docker execution profile security level ${JSON.stringify(root?.securityLevel)}` }); return dockerProfileError({ code: errorPath === "profile.capacity" ? "sandbox.docker-profile-capacity-invalid" : "sandbox.docker-profile-schema-invalid", path: errorPath, message: issue === undefined ? "profile is not a valid Docker execution profile v1" : `${errorPath} ${issue.message}` }); }
export function parseDockerExecutionProfileV1(value: unknown): DockerExecutionProfileV1 { const decoded = Schema.decodeUnknownEither(DockerExecutionProfileV1Schema, ParseOptions)(value); if (Either.isLeft(decoded)) throw schemaError(value, decoded.left); const profile = freezeProfile(decoded.right); const expected = dockerExecutionProfileSemanticPolicyRevisionOf(profile); if (profile.semanticPolicyRevision !== expected) throw dockerProfileError({ code: "sandbox.docker-profile-semantic-policy-mismatch", path: "profile.semanticPolicyRevision", message: `profile.semanticPolicyRevision does not match the canonical semantic policy revision ${expected}`, details: { expected, actual: profile.semanticPolicyRevision } }); return profile; }
export const parseDockerExecutionProfile = parseDockerExecutionProfileV1;
export const decodeDockerExecutionProfileV1 = parseDockerExecutionProfileV1;
export function makeDockerExecutionProfileV1(input: DockerExecutionProfileV1Draft): DockerExecutionProfileV1 { return parseDockerExecutionProfileV1({ ...input, semanticPolicyRevision: dockerExecutionProfileSemanticPolicyRevisionOf(input) }); }
export const createDockerExecutionProfileV1 = makeDockerExecutionProfileV1;
export function isDockerExecutionProfileV1(value: unknown): value is DockerExecutionProfileV1 { try { parseDockerExecutionProfileV1(value); return true; } catch { return false; } }
export function dockerExecutionProfileV1Digest(profile: DockerExecutionProfileV1): string { return `sha256:${digestOf(parseDockerExecutionProfileV1(profile) as unknown as JsonValue)}`; }
export const dockerProfileDigestOf = dockerExecutionProfileV1Digest;
export function dockerProfilePublicSummaryOf(profile: DockerExecutionProfileV1): DockerProfilePublicSummary { const normalized = parseDockerExecutionProfileV1(profile); return Object.freeze({ schemaVersion: 1, profileId: normalized.profileId, securityLevel: normalized.securityLevel, semanticPolicyRevision: normalized.semanticPolicyRevision, capacity: normalized.capacity }); }
