// niceeval/expect：只导出纯 Match factories。Fact、verdict 与 score use 由 context 负责。

export {
  and,
  atLeast,
  atMost,
  commandMatch,
  commandSucceeded,
  defineScoreMatch,
  defineValueMatch,
  equals,
  eventMatch,
  excludes,
  greaterThan,
  includes,
  includesUrl,
  isDefined,
  isFalse,
  isTrue,
  jsonMatch,
  hasSections,
  lessThan,
  matches,
  not,
  or,
  pattern,
  referencesAnyPath,
  satisfies,
  similarity,
  toolMatch,
} from "../assertions/match.ts";

export type {
  AssertionEvent,
  AssertionEventIdentity,
  AssertionEventPosition,
  AssertionToolReference,
  BooleanMatch,
  CommandMatchOptions,
  EventMatch,
  EventOptionsByType,
  LogicalCommandOccurrence,
  Match,
  MatchDomain,
  MatchableEvent,
  ScoreMatch,
  ThresholdedScoreMatch,
  TextMatchOptions,
  ToolMatch,
  ToolMatchOptions,
  ToolStatus,
  ValueMatch,
} from "../assertions/match.ts";
