export {
  attemptOriginRunProjection,
  attemptSlotProjection,
  defineRecordAttachmentProjector,
  selectedRunProjection,
} from "./projector.ts";
export type {
  RecordAttachmentProjector,
  RecordProjection,
} from "./projector.ts";
export { projectAnalysisSample } from "./runtime.ts";
export type { ProjectedRecordAttachmentResult } from "./attachment-result.ts";
export type { ProjectionCoverage } from "./coverage.ts";
export type {
  AttemptAttachmentOwner,
  AttemptOriginRunProjectedEntry,
  AttemptSlotProjectedEntry,
  ProjectedEntry,
  ProjectedSample,
  ProjectedSlotEntry,
  ProjectionAccess,
  ProjectionLimitError,
  RunAttachmentOwner,
  SelectedRunProjectedEntry,
} from "./model.ts";

export {
  assertionSourceSitesProjector,
  assertionsProjector,
  sourcesProjector,
} from "../sources/projector.ts";
export { assembleAttemptSourceTreeV1 } from "../sources/assemble.ts";
export type {
  AssertionSourceFileFrameV1,
  AssertionSourceFrameV1,
  AssertionSourceOccurrenceV1,
  AssertionSourcePackageFrameV1,
  AssertionSourceRoleV1,
  AssertionSourceSendOccurrenceV1,
  AssertionSourceSendSiteV1,
  AssertionSourceSendStatusV1,
  AssertionSourceSiteV1,
  AssertionSourceSitesDocumentV1,
  AssertionSourceSitesEntryV1,
  AssertionSourceSitesProjectionV1,
  AssertionSourceTraceV1,
  AssertionsSourceProjectionV1,
  AttemptSourceAnnotationV1,
  AttemptSourceAssertionsAttachmentV1,
  AttemptSourceEntryUnmappedV1,
  AttemptSourceFileNodeV1,
  AttemptSourcePackageNodeV1,
  AttemptSourceSitesAttachmentV1,
  AttemptSourceTreeAssemblyInputV1,
  AttemptSourceTreeAssemblyIssueV1,
  AttemptSourceTreeAssemblyResultV1,
  AttemptSourceTreeEntryV1,
  AttemptSourceTreeLineV1,
  AttemptSourceTreeNodeV1,
  AttemptSourceTreeSampleV1,
  AttemptSourceTreeSlotV1,
  AttemptSourceTreeSummaryV1,
  AttemptSourceTreeV1,
  AttemptSourceUnavailableAttachmentV1,
  AttemptSourceUnmappedReasonV1,
  AttemptSourceUnmappedV1,
  AttemptSourceUnownedUnmappedV1,
  AttemptSourcesAttachmentV1,
  CanonicalSourcePathV1,
  Sha256Digest,
  SourceCoordinateV1,
  SourceFileItemId,
  SourceFileItemRefV1,
  SourceFileProjectionV1,
  SourceFileV1,
  SourcePackageItemId,
  SourcePackageItemRefV1,
  SourcePackageProjectionV1,
  SourcePackageV1,
  SourcesDocumentV1,
  SourcesProjectionV1,
} from "../sources/model.ts";
