// niceeval/report is the complete public Report authoring surface. Persisted
// Record selection and execution remain internal to the CLI host.
export * from "../analysis/index.ts";
export * from "../projection/index.ts";

export {
  defineCalculation,
  defineDownload,
  definePage,
  definePageFamily,
  reportComponentId,
  reportDownloadPath,
  reportId,
  reportInputs,
  reportInstanceKey,
  reportInstanceKeyFromRecordId,
  reportRoute,
  reportRouteFromKeys,
} from "./author/index.ts";

export {
  AttemptAssessment,
  AttemptSummary,
  Bars,
  Col,
  CopyBlock,
  ExperimentScatter,
  ExperimentTable,
  Grid,
  Hero,
  SampleNotices,
  SampleSummary,
  Section,
  Stat,
  Table,
  aggregate,
  agent,
  costUSD,
  defineComponent,
  defineReport,
  durationMs,
  evalId,
  experiment,
  formatCellText,
  formatMetricValue,
  mean,
  passRate,
  rollup,
  toAttemptFixPrompt,
  toAttemptListRows,
  toAttemptSummary,
  toSummaryItems,
  Fragment,
  jsx,
  jsxs,
} from "./classic/index.ts";
export type {
  AggregationSubject,
  AttemptEvidence,
  AttemptListItem,
  AttemptSummaryData,
  Calculation,
  Cell,
  ClassicComponent,
  ClassicComponentContext,
  ClassicHeroLogo,
  ClassicHeroProps,
  ClassicLocale,
  ClassicReportDefinition,
  ClassicReportPageDefinition,
  ClassicSample,
  ClassicSelectionOrigin,
  CopyBlockContent,
  GroupFunction,
  LocalizedText,
  MetricValue,
  Reducer,
  RollupCalculation,
  RollupOptions,
  Sample,
  SampleSummaryContent,
  StatTone,
  VerdictCounts,
} from "./classic/index.ts";

export type {
  AnyReportCalculation,
  Report,
  ReportCalculation,
  ReportCalculationResults,
  ReportCalculationSet,
  ReportCompleteness,
  ReportComponentContext,
  ReportComponentId,
  ReportDataPlan,
  ReportDataShape,
  ReportDataState,
  ReportDownload,
  ReportDownloadFile,
  ReportDownloadPath,
  ReportId,
  ReportInstanceKey,
  ReportPage,
  ReportPageFamily,
  ReportPathIssue,
  ReportProjectedValues,
  ReportRoute,
} from "./author/index.ts";

export {
  REPORT_DOCUMENT_DEPTH_MAX,
  REPORT_DOCUMENT_NODES_MAX,
  freezeReportDocument,
  reportChart,
  reportCode,
  reportCodeBlock,
  reportDocument,
  reportEmphasis,
  reportLink,
  reportList,
  reportMetric,
  reportParagraph,
  reportSection,
  reportStatus,
  reportTable,
  reportText,
  validateReportDocument,
} from "./semantic/index.ts";

export type {
  ReportBlock,
  ReportChart,
  ReportCode,
  ReportDocumentClosure,
  ReportDocumentIssue,
  ReportDocument,
  ReportDocumentValidation,
  ReportInline,
  ReportList,
  ReportMetric,
  ReportParagraph,
  ReportScalar,
  ReportSection,
  ReportStatus,
  ReportTable,
} from "./semantic/index.ts";

// Completed execution data is immutable and safe for an author to inspect.
// Constructors, host callbacks, and scheduling mechanics stay private.
export type {
  ReportExecution,
} from "./execution/model.ts";
export type {
  ReportCalculationExecutionResult,
  ReportCalculationResult,
  ReportDownloadResult,
  ReportPageFamilyResult,
  ReportPageResult,
  ReportProjectionId,
  ReportProjectionSummary,
} from "./execution/results.ts";
export type {
  ReportExecutionProblem,
  ReportProblem,
  ReportProblemId,
  ReportProblemTable,
  ReportProblemTableEntry,
  ReportRecordedDataProblem,
} from "./execution/problems.ts";

export {
  basalt,
  chalk,
  defineTheme,
} from "./host/theme.ts";
export type {
  ReportTheme,
  ThemeColor,
  ThemeDefinition,
  ThemeFontSize,
  ThemeFontTokens,
  ThemeHex,
  ThemeRadius,
  ThemeSeries,
} from "./host/theme.ts";
