packages: []
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.8'
  - '@ai-sdk/openai@4.0.5'
  - '@ai-sdk/react@4.0.5'
  - '@ai-sdk/provider-utils@5.0.3'
  - ai@7.0.11
  - niceeval@0.1.1
overrides:
  shell-quote: 1.9.0
  ai: 7.0.11
  niceeval: link:../../../..
