import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { Deferred, Effect, Fiber } from "effect";
import { decodePayload, readRegistry, writeRegistry } from "../coordination/platform/sqlite-registries.ts";
export const SHARED_STATE_LEASE_HEARTBEAT_INTERVAL_MS=10_000;
export type SharedStateLeaseStatus="active"|"recovering";
export interface SharedStateRecoveryActor{readonly pid:number;readonly host:string;readonly processIdentity:string;readonly startedAt:string}
export interface SharedStateLeaseRecord{readonly key:string;readonly experimentId:string;readonly ownerToken:string;readonly pid:number;readonly host:string;readonly processIdentity:string;readonly acquiredAt:string;readonly heartbeatAt:string;readonly status:SharedStateLeaseStatus;readonly generation:number;readonly parentGeneration:number;readonly recoveryId?:string;readonly recoveryActor?:SharedStateRecoveryActor}
export interface SharedStateLeaseIdentity{readonly experimentId:string;readonly pid:number;readonly host:string;readonly processIdentity:string}
export class SharedStateLeaseError extends Error{constructor(readonly code:"shared-state-lease-invalid"|"shared-state-lease-owner-mismatch"|"shared-state-lease-missing"|"shared-state-owner-still-live"|"shared-state-process-identity-unavailable"|"shared-state-recovery-confirmation-required"|"shared-state-recovery-state-mismatch"|"shared-state-recovery-in-progress"|"shared-state-recovery-identity-unavailable",message:string){super(message);this.name="SharedStateLeaseError"}}
export interface SharedStateLeaseEffectClaim{readonly ownerToken:string;readonly release:Effect.Effect<void,SharedStateLeaseError|unknown>;readonly abandon:Effect.Effect<void>}
export interface AcquireSharedStateLeaseEffectResult{readonly claim:SharedStateLeaseEffectClaim}
export type ExplicitSharedStateRecovery={readonly _tag:"Claimed";readonly record:SharedStateLeaseRecord;readonly recoveryId:string}|{readonly _tag:"AlreadyReleased";readonly record:SharedStateLeaseRecord};
interface Head{kind:"active"|"recovering"|"free";record:SharedStateLeaseRecord}
const io=<A>(fn:()=>A):Effect.Effect<A,unknown>=>Effect.try({try:fn,catch:(cause)=>cause});
export function sharedStateLeasesDirOf(root:string):string{return join(root,"shared-state-leases")}
function head(root:string,key:string):Head|undefined{return readRegistry(root,(db)=>{const row=db.prepare("SELECT state_kind,payload FROM shared_state_generations WHERE state_key=? ORDER BY generation DESC LIMIT 1").get(key) as {state_kind:string;payload:unknown}|undefined;return row?{kind:row.state_kind as Head["kind"],record:decodePayload<SharedStateLeaseRecord>(row.payload as never)}:undefined})}
function publish(root:string,expected:number,kind:Head["kind"],record:SharedStateLeaseRecord):boolean{return writeRegistry(root,(db,encode)=>{const row=db.prepare("SELECT max(generation) generation FROM shared_state_generations WHERE state_key=?").get(record.key) as {generation:number|null};if(Number(row.generation??0)!==expected)return false;db.prepare("INSERT INTO shared_state_generations(state_key,generation,parent_generation,state_kind,owner_token,owner_pid,owner_host,owner_process_identity,heartbeat_at,payload) VALUES(?,?,?,?,?,?,?,?,?,?)").run(record.key,record.generation,record.parentGeneration,kind,record.ownerToken,record.pid,record.host,record.processIdentity,record.heartbeatAt,encode(record));return true})}
export function readSharedStateLeaseEffect(root:string,key:string):Effect.Effect<SharedStateLeaseRecord|undefined,SharedStateLeaseError|unknown>{return io(()=>{const h=head(root,key);return h?.kind==="free"?undefined:h?.record})}
export function readSharedStateLeaseRecoveryTargetEffect(root:string,key:string):Effect.Effect<SharedStateLeaseRecord|undefined,SharedStateLeaseError|unknown>{return io(()=>head(root,key)?.record)}
function errno(c:unknown):string|undefined{return typeof c==="object"&&c!==null&&"code" in c?String((c as {code:unknown}).code):undefined}
export function processIdentityForPidEffect(pid:number):Effect.Effect<string|undefined,unknown>{return Effect.tryPromise({try:async()=>{if(process.platform==="linux"){try{const raw=await readFile(`/proc/${pid}/stat`,"utf8");const i=raw.lastIndexOf(")");if(i<0)throw new Error("invalid process identity");const f=raw.slice(i+2).trim().split(/\s+/u);if(["Z","X","x"].includes(f[0]??""))return undefined;if(!f[19]||!/^\d+$/u.test(f[19]))throw new Error("invalid process identity");return`linux-starttime:${f[19]}`}catch(c){if(errno(c)==="ENOENT")return undefined;throw c}}return await new Promise<string|undefined>((resolve,reject)=>execFile("ps",["-o","lstart=","-p",String(pid)],{encoding:"utf8"},(e,out)=>e?(out.trim()?reject(e):resolve(undefined)):resolve(out.trim()?`ps-lstart:${out.trim()}`:undefined)))},catch:(cause)=>cause})}
export function currentProcessIdentityEffect():Effect.Effect<string,SharedStateLeaseError|unknown>{return processIdentityForPidEffect(process.pid).pipe(Effect.flatMap((v)=>v?Effect.succeed(v):Effect.fail(new SharedStateLeaseError("shared-state-process-identity-unavailable","NiceEval could not establish this process identity; sharedState fails closed rather than coordinating from a PID alone."))))}
function same(a:SharedStateLeaseRecord,b:SharedStateLeaseRecord):boolean{return a.key===b.key&&a.ownerToken===b.ownerToken&&a.generation===b.generation&&a.pid===b.pid&&a.host===b.host&&a.processIdentity===b.processIdentity}
function abortError(signal?:AbortSignal):Error{const e=signal?.reason instanceof Error?signal.reason:new Error("aborted while waiting for shared-state recovery");e.name="AbortError";return e}
function wait(ms:number,signal?:AbortSignal):Effect.Effect<void,Error>{return Effect.tryPromise({try:()=>new Promise<void>((resolve,reject)=>{if(signal?.aborted)return reject(abortError(signal));const timer=setTimeout(resolve,ms);signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(abortError(signal))},{once:true})}),catch:(c)=>c as Error})}
export function acquireSharedStateLeaseEffect(root:string,key:string,identity:SharedStateLeaseIdentity,opts:{readonly signal?:AbortSignal;readonly pollIntervalMs?:number;readonly heartbeatIntervalMs?:number;readonly onWaitStart?:(holder:SharedStateLeaseRecord)=>void}={}):Effect.Effect<AcquireSharedStateLeaseEffectResult,SharedStateLeaseError|unknown>{
  const token=randomUUID(); let reported=false;
  const acquire=():Effect.Effect<SharedStateLeaseRecord,unknown>=>Effect.suspend(()=>io(()=>head(root,key)).pipe(Effect.flatMap((h)=>{
    if(h&&h.kind!=="free"){
      if(!reported){reported=true;opts.onWaitStart?.(h.record)}
      return wait(opts.pollIntervalMs??SHARED_STATE_LEASE_HEARTBEAT_INTERVAL_MS,opts.signal).pipe(Effect.andThen(acquire()));
    }
    const parent=h?.record.generation??0; const now=new Date().toISOString();
    const record:SharedStateLeaseRecord={key,experimentId:identity.experimentId,ownerToken:token,pid:identity.pid,host:identity.host,processIdentity:identity.processIdentity,acquiredAt:now,heartbeatAt:now,status:"active",generation:parent+1,parentGeneration:parent};
    return io(()=>publish(root,parent,"active",record)).pipe(Effect.flatMap((ok)=>ok?Effect.succeed(record):acquire()));
  })));
  return acquire().pipe(Effect.flatMap((record)=>{
    const pulse=Effect.forever(Effect.sleep(opts.heartbeatIntervalMs??SHARED_STATE_LEASE_HEARTBEAT_INTERVAL_MS).pipe(Effect.andThen(io(()=>writeRegistry(root,(db,encode)=>{
      const row=db.prepare("SELECT state_kind,payload FROM shared_state_generations WHERE state_key=? ORDER BY generation DESC LIMIT 1").get(key) as {state_kind:string;payload:unknown}|undefined;
      const current=row?decodePayload<SharedStateLeaseRecord>(row.payload as never):undefined;
      if(row?.state_kind!=="free"&&current&&same(current,record)){const updated={...record,heartbeatAt:new Date().toISOString()};db.prepare("UPDATE shared_state_generations SET heartbeat_at=?,payload=? WHERE state_key=? AND generation=? AND owner_token=?").run(updated.heartbeatAt,encode(updated),key,record.generation,record.ownerToken)}
    })).pipe(Effect.ignore))));
    return Effect.forkDetach(pulse).pipe(Effect.map((fiber)=>{
      let stopped=false;
      const stop=Effect.suspend(()=>{if(stopped)return Effect.void;stopped=true;return Fiber.interrupt(fiber).pipe(Effect.asVoid)});
      const release=stop.pipe(Effect.andThen(io(()=>{const h=head(root,key);if(!h||h.kind==="free"||!same(h.record,record))throw new SharedStateLeaseError("shared-state-lease-owner-mismatch",`sharedState lease ${JSON.stringify(key)} exact owner generation no longer matches.`);const next={...record,generation:record.generation+1,parentGeneration:record.generation,heartbeatAt:new Date().toISOString()};if(!publish(root,record.generation,"free",next))throw new SharedStateLeaseError("shared-state-lease-owner-mismatch","sharedState lease changed during release")})));
      return {claim:{ownerToken:token,release,abandon:stop}};
    }));
  }));
}
function stopped(record:SharedStateLeaseRecord,host:string):Effect.Effect<boolean,unknown>{return record.host!==host?Effect.succeed(true):processIdentityForPidEffect(record.pid).pipe(Effect.map((v)=>v===undefined||v!==record.processIdentity))}
export function beginExplicitSharedStateRecoveryEffect(input:{readonly niceevalRoot:string;readonly key:string;readonly ownerToken:string;readonly localHost:string;readonly confirmOwnerTerminated:boolean;readonly confirmRemoteQuiesced:boolean}):Effect.Effect<ExplicitSharedStateRecovery,SharedStateLeaseError|unknown>{return Effect.gen(function*(){if(!input.confirmOwnerTerminated||!input.confirmRemoteQuiesced)return yield* new SharedStateLeaseError("shared-state-recovery-confirmation-required","Shared-state recovery requires explicit confirmations.");const h=yield* io(()=>head(input.niceevalRoot,input.key));if(!h)return yield* new SharedStateLeaseError("shared-state-lease-missing",`No sharedState lease exists for ${JSON.stringify(input.key)}.`);if(h.record.ownerToken!==input.ownerToken)return yield* new SharedStateLeaseError("shared-state-lease-owner-mismatch","The supplied owner token does not own this key.");if(h.kind==="free")return{_tag:"AlreadyReleased",record:h.record};if(!(yield* stopped(h.record,input.localHost)))return yield* new SharedStateLeaseError(h.kind==="recovering"?"shared-state-recovery-in-progress":"shared-state-owner-still-live","The exact owner process is still live.");const processIdentity=yield* currentProcessIdentityEffect();const recoveryId=randomUUID();const actor={pid:process.pid,host:input.localHost,processIdentity,startedAt:new Date().toISOString()};const record={...h.record,status:"recovering" as const,generation:h.record.generation+1,parentGeneration:h.record.generation,recoveryId,recoveryActor:actor,heartbeatAt:new Date().toISOString()};if(!(yield* io(()=>publish(input.niceevalRoot,h.record.generation,"recovering",record))))return yield* new SharedStateLeaseError("shared-state-recovery-state-mismatch","sharedState generation changed during recovery.");return{_tag:"Claimed",record,recoveryId}})}
export function completeExplicitSharedStateRecoveryEffect(input:{readonly niceevalRoot:string;readonly key:string;readonly ownerToken:string;readonly recoveryId:string;readonly localHost:string}):Effect.Effect<void,SharedStateLeaseError|unknown>{return Effect.gen(function*(){const identity=yield* currentProcessIdentityEffect();yield* io(()=>{const h=head(input.niceevalRoot,input.key);if(!h||h.kind!=="recovering"||h.record.ownerToken!==input.ownerToken||h.record.recoveryId!==input.recoveryId||h.record.recoveryActor?.pid!==process.pid||h.record.recoveryActor.host!==input.localHost||h.record.recoveryActor.processIdentity!==identity)throw new SharedStateLeaseError("shared-state-recovery-state-mismatch","sharedState lease no longer matches this recovery actor.");const next={...h.record,generation:h.record.generation+1,parentGeneration:h.record.generation,heartbeatAt:new Date().toISOString()};if(!publish(input.niceevalRoot,h.record.generation,"free",next))throw new SharedStateLeaseError("shared-state-recovery-state-mismatch","sharedState generation changed during recovery completion.")})})}
