import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Effect, Result, Schema } from "effect";
import { decodePayload, readRegistry, readRows, writeRegistry } from "../coordination/platform/sqlite-registries.ts";
import { hashEntryId } from "../shared/entry-file-store.ts";
import { processIdentityForPidEffect } from "./shared-state-lease.ts";

export interface TeardownRegistration { experimentId: string; selectedEvalIds: readonly string[]; pid: number; host: string; startedAt: string }
const Positive = Schema.Number.pipe(Schema.check(Schema.makeFilter((n) => Number.isSafeInteger(n) && n > 0)));
const Timestamp = Schema.String.pipe(Schema.check(Schema.makeFilter((s) => Number.isFinite(Date.parse(s)))));
const Registration = Schema.Struct({ experimentId: Schema.String, selectedEvalIds: Schema.Array(Schema.String), pid: Positive, host: Schema.String, startedAt: Timestamp });
function decode(value: unknown): TeardownRegistration | undefined { const result = Schema.decodeUnknownResult(Registration)(value); return Result.isSuccess(result) ? result.success : undefined; }
export function teardownsDirOf(root: string): string { return join(root, "teardowns"); }
export function teardownEntryId(experimentId: string, pid: number): string { return hashEntryId([experimentId, String(pid)]); }
export function writeTeardownRegistrationEffect(root: string, entry: TeardownRegistration): Effect.Effect<void, unknown> { return Effect.try({ try: () => writeRegistry(root, (db, encode) => { db.prepare(`INSERT INTO teardown_obligations(obligation_id,experiment_id,owner_pid,owner_host,payload) VALUES(?,?,?,?,?) ON CONFLICT(obligation_id) DO UPDATE SET owner_host=excluded.owner_host,payload=excluded.payload`).run(teardownEntryId(entry.experimentId, entry.pid), entry.experimentId, entry.pid, entry.host, encode(entry)); }), catch: (cause) => cause }); }
export function readTeardownRegistrationEffect(root: string, experimentId: string, pid: number): Effect.Effect<TeardownRegistration | undefined, unknown> { return Effect.try({ try: () => readRegistry(root, (db) => { const row = db.prepare("SELECT payload FROM teardown_obligations WHERE experiment_id=? AND owner_pid=?").get(experimentId, pid) as { payload: unknown } | undefined; const value = row === undefined ? undefined : decode(decodePayload(row.payload as never)); return value?.experimentId === experimentId && value.pid === pid ? value : undefined; }), catch: (cause) => cause }); }
export const readExactTeardownRegistrationEffect = readTeardownRegistrationEffect;
export interface ExactTeardownRegistrationOwner { readonly experimentId: string; readonly pid: number; readonly host: string; readonly processIdentity: string }
export function isExactTeardownRegistrationOwnerTerminatedEffect(input: { readonly registration: TeardownRegistration; readonly owner: ExactTeardownRegistrationOwner; readonly currentHost: string }): Effect.Effect<boolean, unknown> { if (input.registration.experimentId !== input.owner.experimentId || input.registration.pid !== input.owner.pid || input.registration.host !== input.owner.host) return Effect.fail(new Error("teardown registration does not match the immutable sharedState owner identity")); if (input.owner.host !== input.currentHost) return Effect.succeed(true); return processIdentityForPidEffect(input.owner.pid).pipe(Effect.map((identity) => identity === undefined || identity !== input.owner.processIdentity)); }
export function readTeardownRegistrationsEffect(root: string): Effect.Effect<{ id: string; entry: TeardownRegistration }[], unknown> { return Effect.try({ try: () => readRegistry(root, (db) => readRows(db, "SELECT obligation_id,payload FROM teardown_obligations ORDER BY experiment_id,owner_pid").flatMap((row) => { const entry = decode(decodePayload(row.payload)); return entry === undefined ? [] : [{ id: String(row.obligation_id), entry }]; })), catch: (cause) => cause }); }
export function removeTeardownRegistrationIfPresentEffect(root: string, id: string): Effect.Effect<boolean, unknown> { return Effect.try({ try: () => writeRegistry(root, (db) => Number(db.prepare("DELETE FROM teardown_obligations WHERE obligation_id=?").run(id).changes) === 1), catch: (cause) => cause }); }
function isPidTerminal(pid: number): boolean { try { if (process.platform === "linux") { const raw = readFileSync(`/proc/${pid}/stat`, "utf8"); const i = raw.lastIndexOf(")"); return i >= 0 && ["Z", "X", "x"].includes(raw.slice(i + 2).trim().split(/\s+/u)[0] ?? ""); } process.kill(pid, 0); return false; } catch (cause) { return (cause as NodeJS.ErrnoException).code !== "EPERM"; } }
export function isOrphanedTeardownRegistration(entry: TeardownRegistration, currentHost: string): boolean { return entry.host === currentHost && isPidTerminal(entry.pid); }
export function orphanedTeardownReminderEffect(root: string, recovering: ReadonlySet<string>, host: string): Effect.Effect<string | undefined, unknown> { return readTeardownRegistrationsEffect(root).pipe(Effect.map((rows) => { const lines = rows.filter(({ entry }) => isOrphanedTeardownRegistration(entry, host) && !recovering.has(entry.experimentId)).map(({ entry }) => `unfinished experiment teardown for "${entry.experimentId}" from a killed run — niceeval exp ${entry.experimentId} --teardown\n`); return lines.length ? lines.join("") : undefined; })); }
