// `niceeval/analysis` is the public author surface for statistical meaning.
// The separate public Host SDK issues Sample capabilities; Record readers stay
// in its private binding map, while Report receives rows, frames, and values.
export {
  aggregate,
  attemptEvidenceView,
  attemptObservabilityView,
  fileChangesView,
  query,
  sandboxHistoryView,
  sourceNavigationView,
  sourcesView,
} from "./api.ts";

export {
  allLogicalSlots,
  attemptLatencyMs,
  attemptTokens,
  attemptPassed,
  attemptToolFailure,
  defineDimension,
  defineMeasure,
  definePopulation,
  defineRelation,
  latestCompletedAttempt,
  logicalSlotMembers,
  logicalSlots,
  mean,
  oneValue,
  partial,
  ratio,
  requireSameProducer,
  retainContributingEvidence,
  sum,
  sumAcrossSlots,
} from "./definitions.ts";

export {
  builtInPricingProfile,
  costUSD,
  definePricingProfile,
  totalCostUSD,
} from "./cost.ts";

export {
  decodeSampleSnapshot,
  encodeSampleSnapshot,
  narrowSample,
} from "../sample/capability.ts";

export {
  experimentComparisonScope,
  experimentGroups,
} from "./experiment-groups.ts";

export type {
  AggregateRequest,
  AggregateRow,
  AttemptEvidenceDomainView,
  AttemptObservabilityDomainView,
  BuiltinDomainView,
  BuiltinDomainViewKind,
  ClosedDomainEntry,
  DimensionSet,
  DomainViewQuery,
  DomainViewRequest,
  FileChangesDomainView,
  FrameQuery,
  MeasureSet,
  MeasureCell,
  SandboxHistoryDomainView,
  SemanticFrame,
  SemanticRow,
  SourceNavigationDomainView,
  SourcesDomainView,
} from "./api.ts";

export type {
  CostBasis,
  CostComponent,
  CostCoverageReason,
  CostCoverageReasonCode,
  CostLedgerEntry,
  CostMeasure,
  CostMetricValue,
  CostProjectionAggregate,
  CostProjectionKnown,
  CostProjectionMigrationRequired,
  CostProjectionProfile,
  CostProjectionState,
  CostProjectionUnavailable,
  CostProjectionValue,
  EstimatedRequestCostComponent,
  EstimatedTokenCostComponent,
  ObservedCostComponent,
  ObservedOtherCurrency,
  PricedCoverage,
  PricedCoverageInput,
  PricingCharge,
  PricingChargeInput,
  PricingCoverage,
  PricingCoverageId,
  PricingCoverageInput,
  PricingDisplay,
  PricingDisplayInput,
  PricingEffectiveCondition,
  PricingEffectiveConditionInput,
  PricingProfile,
  PricingProfileContentIdentity,
  PricingProfileInput,
  PricingProvenance,
  PricingProvenanceInput,
  PricingSelector,
  PricingSelectorInput,
  ProjectedMoney,
  RequestPricingCharge,
  RequestPricingChargeInput,
  TokenPricingCharge,
  TokenPricingChargeInput,
  UnpricedCoverage,
  UnpricedCoverageInput,
} from "./cost.ts";

export type {
  AttemptEvidenceDomainDetail,
  AttemptObservabilityDomainDetail,
  BuiltinDomainDetail,
  ClosedBlobContent,
  ClosedAssertionCollectionReceipt,
  ClosedAssertionContribution,
  ClosedAssertionCoverage,
  ClosedAssertionLimitation,
  ClosedAssertionDecision,
  ClosedAssertionDisplay,
  ClosedAssertionFactField,
  ClosedAssertionFactValue,
  ClosedAssertionObserved,
  ClosedAssertionPolicy,
  ClosedAssertionSource,
  ClosedAssertionSourceSite,
  ClosedCommandEntry,
  ClosedCommandInvocation,
  ClosedCommandOutcome,
  ClosedCommandStream,
  ClosedCommandWorkingDirectory,
  ClosedCommandsDetail,
  ClosedConversationDetail,
  ClosedConversationItem,
  ClosedConversationTurn,
  ClosedDiagnosticRedaction,
  ClosedDiagnosticsDetail,
  ClosedFileChange,
  ClosedFileChangeEndpoint,
  ClosedFileChangeWindow,
  ClosedFileChangesAttribution,
  ClosedFileChangesCollection,
  ClosedFileChangesCollectionLimitation,
  ClosedFileRevision,
  ClosedSourceFrame,
  ClosedSourceDependency,
  ClosedSourceState,
  ClosedTimingDetail,
  ClosedTimingInterval,
  ClosedTraceCollection,
  ClosedUsageDetail,
  ClosedUsageObservation,
  FileChangesDomainDetail,
  FileChangesNet,
  SandboxHistoryDomainDetail,
  SourceNavigationDomainDetail,
  SourcesDomainDetail,
} from "./domain-view.ts";

export type {
  AcrossSlotsReduction,
  AnalysisDefinitionError,
  AnalysisInput,
  Denominator,
  Dimension,
  DimensionValue,
  EvidencePolicy,
  LogicalSlot,
  Measure,
  MeasureOptions,
  MissingPolicy,
  Population,
  PopulationMembers,
  ProducerPolicy,
  Relation,
  RelationTarget,
  WithinAttemptReduction,
  WithinSlotReduction,
} from "./definitions.ts";

export type {
  AnalysisCurrentSlotIdentity,
  AnalysisSlotOccurrenceIdentity,
  AnalysisRun,
  AnalysisRunContext,
  AnalysisRunExecution,
  AnalysisSelectionRequest,
  AnalysisSelectionSummary,
  EvalId,
  ExecutionIdentityDigest,
  AnalysisSlot,
  AnalysisIssue,
  AnalysisRequestError,
  SampleClosedError,
  SampleIdentity,
  AttemptId,
  ClosedRows,
  ClosedRowsIdentity,
  DomainView,
  EvidenceIdentity,
  EvidenceRef,
  ExperimentId,
  ExperimentComparison,
  ExperimentComparisonScope,
  ExperimentEvalCoverage,
  ExperimentGroupIdentity,
  JsonValue,
  MeasureFormat,
  MetricBasis,
  MetricState,
  MetricValue,
  PopulationIdentity,
  ProducerIdentity,
  RunId,
  Sample,
  SampleCoverage,
  SampleSelector,
  SampleSnapshot,
  SampleSnapshotCodecError,
  SlotId,
} from "./contracts.ts";

export type { ExperimentGroupSummary } from "./experiment-groups.ts";

export { ExperimentIdSchema } from "../record/codec/identifiers.ts";
