packages: []
allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
minimumReleaseAgeExclude:
  - niceeval@0.1.0-alpha.0
overrides:
  shell-quote: 1.9.0
  niceeval: link:../../..
