export {
  INSPECTION_OPERATION_IDS,
  QUERY_PROTOCOL,
  decodeInspectionDocument,
  narrowInspectionExplanation,
  narrowInspectionSuccess,
  type InspectionDiscoveryDocument as QueryDiscoveryDocument,
  type InspectionDocument as QueryDocument,
  type InspectionExplanationDocumentFor as QueryExplanationDocumentFor,
  type InspectionFailureDocument as QueryFailureDocument,
  type InspectionOperation,
  type InspectionRequest,
  type InspectionOperationId as QueryOperationId,
  type InspectionSuccessDocumentFor as QuerySuccessDocumentFor,
} from "niceeval/inspection";
