import { Effect } from "effect";
import { Argument as Args, Command, Flag as Options } from "effect/unstable/cli";
import { defineDocsCommandContribution, deliverDomainResult, jsonDocument, type TerminalDeliverySink } from "./contribution.js";
import { addCaseIssue, addCaseRegression, applyCaseMigration, attachCase, auditCases, createOwner, inventoryCases, listCases, moveCase, planCaseMigration, renderCaseCommandError, renderCaseReceipt, retireCase, retireCaseIssue, retireCaseRegression, retireOwner, setOwnerContract, showCase } from "./test-case/cli-runtime.js";

const json = Options.boolean("json").pipe(Options.withDefault(false), Options.withDescription("Emit a machine-readable JSON receipt."));
const dryRun = Options.boolean("dry-run").pipe(Options.withDefault(false), Options.withDescription("Plan and validate without writing files."));
const expectedDigest = Options.string("expected-digest").pipe(Options.optional, Options.withDescription("Expected sha256 sidecar preimage from show/list."));
const receipt = Options.string("receipt").pipe(Options.optional, Options.withDescription("Consume an existing native runner inventory receipt."));
const inventoryOptions = { repo: Options.string("repo").pipe(Options.withDefault("niceeval")), executor: Options.choice("executor", ["vitest", "playwright"] as const).pipe(Options.withDefault("vitest")), cwd: Options.string("cwd").pipe(Options.withDefault(".")), checkout: Options.string("checkout").pipe(Options.withDefault("HEAD")), receipt, nativeArgs: Options.string("native-args").pipe(Options.optional, Options.withDescription("JSON array of native runner arguments.")), forMigration: Options.boolean("for-migration").pipe(Options.withDefault(false), Options.withDescription("Allocate permanent IDs for tokenless legacy cases and emit a migration-only receipt.")) };
const mutationOptions = { expectedDigest, dryRun, json };
function run<A, E, R>(deliver: TerminalDeliverySink, program: Effect.Effect<A, E, R>, structured: boolean) { return deliverDomainResult(program, structured, { success: (value, asJson) => asJson ? jsonDocument(value) : renderCaseReceipt(value), failure: renderCaseCommandError }, deliver); }

function makeTestCommand(deliver: TerminalDeliverySink) {
  const inventory = Command.make("inventory", { ...inventoryOptions, json }, (o) => run(deliver, inventoryCases(o), o.json)).pipe(Command.withDescription("Collect cases through the native E2E runner, or validate and consume its receipt."));
  const list = Command.make("list", { pattern: Args.string("pattern").pipe(Args.optional), history: Options.boolean("history").pipe(Options.withDefault(false)), receipt, json }, (o) => run(deliver, listCases(o), o.json)).pipe(Command.withDescription("List case selectors and current sidecar relations; optionally consume inventory evidence."));
  const show = Command.make("show", { selector: Args.string("path#caseId"), history: Options.boolean("history").pipe(Options.withDefault(false)), receipt, json }, (o) => run(deliver, showCase(o), o.json)).pipe(Command.withDescription("Show one exact case selector, its digest, owner, regressions, issues, and history."));
  const audit = Command.make("audit", { checkout: Options.string("checkout").pipe(Options.withDefault("HEAD")), json }, (o) => run(deliver, auditCases(o), o.json)).pipe(Command.withDescription("Prepare every registered E2E repo and report uncovered Use Cases, missing live-case relations, and orphaned relations."));
  const ownerCreate = Command.make("create", { owner: Args.string("owner-ref"), contract: Options.string("contract"), description: Options.string("description"), ...mutationOptions }, (o) => run(deliver, createOwner(o), o.json)).pipe(Command.withDescription("Create a managed testing-owner anchor with one Feature or leaf Use Case contract."));
  const ownerSet = Command.make("set", { owner: Args.string("owner-ref"), contract: Options.string("contract"), ...mutationOptions }, (o) => run(deliver, setOwnerContract(o), o.json)).pipe(Command.withDescription("Change an existing owner's exact Feature or leaf Use Case contract and append history."));
  const ownerRetire = Command.make("retire", { owner: Args.string("owner-ref"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireOwner(o), o.json)).pipe(Command.withDescription("Retire an owner only when no live case refers to it; preserve managed history."));
  const owner = Command.make("owner").pipe(Command.withDescription("Manage testing-owner contract anchors."), Command.withSubcommands([ownerCreate, ownerSet, ownerRetire]));
  const attach = Command.make("attach", { selector: Args.string("path#caseId"), owner: Options.string("owner"), receipt: Options.string("receipt").pipe(Options.withDescription("Native inventory receipt proving this collected case.")), ...mutationOptions }, (o) => run(deliver, attachCase(o), o.json)).pipe(Command.withDescription("Attach an inventoried case to an owner; creates the adjacent sidecar when absent."));
  const move = Command.make("move", { selector: Args.string("old-path#caseId"), to: Options.string("to").pipe(Options.withDescription("New repository-relative test path.")), receipt: Options.string("receipt").pipe(Options.withDescription("Fresh native inventory receipt proving the move.")), ...mutationOptions }, (o) => run(deliver, moveCase(o), o.json)).pipe(Command.withDescription("Atomically move case ownership after runner evidence proves the new path replaced the old path."));
  const retireCaseCommand = Command.make("retire", { selector: Args.string("path#caseId"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCase(o), o.json)).pipe(Command.withDescription("Retire a case into its permanent tombstone."));
  const caseCommand = Command.make("case").pipe(Command.withDescription("Manage case identity lifecycle."), Command.withSubcommands([attach, move, retireCaseCommand]));
  const regressionAdd = Command.make("add", { selector: Args.string("path#caseId"), memory: Options.string("memory"), red: Options.string("red"), green: Options.string("green"), certificate: Options.string("certificate"), inventoryReceipt: Options.string("inventory-receipt"), ...mutationOptions }, (o) => run(deliver, addCaseRegression(o), o.json)).pipe(Command.withDescription("Attach an open Problem only after formal red/green and complete takeover evidence validate for this inventoried case."));
  const regressionRetire = Command.make("retire", { selector: Args.string("path#caseId"), memory: Options.string("memory"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCaseRegression(o), o.json)).pipe(Command.withDescription("Retire a regression; resolved Problems must be reopened first."));
  const regression = Command.make("regression").pipe(Command.withDescription("Manage zero or more Problem regressions per case."), Command.withSubcommands([regressionAdd, regressionRetire]));
  const issueAdd = Command.make("add", { selector: Args.string("path#caseId"), url: Options.string("url"), provenance: Options.choice("provenance", ["direct"] as const), verificationReceipt: Options.string("verification-receipt").pipe(Options.optional, Options.withDescription("Injected already-verified read-only receipt for isolated fixtures.")), ...mutationOptions }, (o) => run(deliver, addCaseIssue(o), o.json)).pipe(Command.withDescription("Read-only verify a same-repository canonical non-PR Issue with direct case provenance, then attach it locally."));
  const issueRetire = Command.make("retire", { selector: Args.string("path#caseId"), url: Options.string("url"), reason: Options.string("reason"), ...mutationOptions }, (o) => run(deliver, retireCaseIssue(o), o.json)).pipe(Command.withDescription("Retire one current Issue relation without mutating GitHub."));
  const issue = Command.make("issue").pipe(Command.withDescription("Manage zero or more verified Issue relations per case."), Command.withSubcommands([issueAdd, issueRetire]));
  const migratePlan = Command.make("plan", { test: Args.string("test-path").pipe(Args.optional), receipt: Options.string("receipt").pipe(Options.withDescription("Native inventory receipt.")), mapping: Options.string("mapping").pipe(Options.withDescription("Explicit JSON mapping for every legacy relation in multi-case files.")), json }, (o) => run(deliver, planCaseMigration(o), o.json)).pipe(Command.withDescription("Create a Git-private, digest-bound migration manifest using explicit per-case legacy mappings."));
  const migrateApply = Command.make("apply", { manifest: Options.string("manifest"), dryRun, json }, (o) => run(deliver, applyCaseMigration(o), o.json)).pipe(Command.withDescription("CAS-validate and atomically apply one complete, unused migration manifest."));
  const migrate = Command.make("migrate").pipe(Command.withDescription("Safely migrate legacy file headers in two explicit phases."), Command.withSubcommands([migratePlan, migrateApply]));
  return Command.make("test").pipe(Command.withDescription("Manage runner-inventoried E2E cases and their sidecar-owned relations."), Command.withSubcommands([inventory, audit, list, show, owner, caseCommand, regression, issue, migrate]));
}
export const testCommandContribution = defineDocsCommandContribution({ name: "test", summary: "Manage runner-inventoried E2E case relations.", makeCommand: makeTestCommand });
