// niceeval/analysis owns the public AnalysisSample selection surface. The
// legacy sample module remains package-private while Record and Report move to
// their finalized boundaries.
export {
  decodeAnalysisSample,
  encodeAnalysisSample,
  ExperimentIdSchema,
  narrowAnalysisSample,
  narrowAnalysisSampleHandle,
  selectAnalysisSample,
  selectExplicitRuns,
  selectLatestRuns,
} from "../sample/analysis.ts";

export type {
  AnalysisBaseSlot,
  AnalysisSampleCodecError,
  AnalysisLimitExceededError,
  AnalysisLatestIndeterminateError,
  AnalysisRun,
  AnalysisRunInvalidError,
  AnalysisRunNotFoundError,
  AnalysisSample,
  AnalysisSampleHandle,
  AnalysisSampleSelector,
  AnalysisSelectionError,
  AnalysisSelectionInvalidError,
  AnalysisSelectionRequest,
  AnalysisSelectionSummary,
  AnalysisSlot,
  AnalysisSlotRef,
  AttemptId,
  CoreInvalidAnalysisSlot,
  ExcludedAnalysisSlot,
  ExperimentId,
  ExplicitRunsAnalysisInput,
  IncludedAnalysisSlot,
  LatestRunsAnalysisInput,
  NonEmptyRecordIssues,
  NotRecordedAnalysisSlot,
  RecordAttemptRef,
  RecordHandleInvalid,
  RecordIoError,
  RecordIssue,
  RecordPermissionError,
  RecordReadError,
  RecordReaderClosed,
  RunId,
  SlotId,
  UtcMillis,
} from "../sample/analysis.ts";
