// `niceeval/analysis` is the public author surface for statistical meaning.
// The separate public Host SDK issues Sample capabilities; Record readers stay
// in its private binding map, while Report receives rows, frames, and values.
export {
  aggregate,
  attemptEvidenceView,
  attemptObservabilityView,
  fileChangesView,
  query,
  sandboxHistoryView,
  sourcesView,
} from "./api.ts";

export {
  allLogicalSlots,
  attemptLatencyMs,
  attemptTokens,
  attemptPassed,
  attemptToolFailure,
  costUSD,
  defineDimension,
  defineMeasure,
  definePopulation,
  defineRelation,
  latestCompletedAttempt,
  logicalSlotMembers,
  logicalSlots,
  mean,
  oneValue,
  partial,
  ratio,
  requireSameProducer,
  retainContributingEvidence,
  sum,
  sumAcrossSlots,
  totalCostUSD,
} from "./definitions.ts";

export {
  decodeSampleSnapshot,
  encodeSampleSnapshot,
  narrowSample,
} from "../sample/capability.ts";

export type {
  AggregateRequest,
  AggregateRow,
  AttemptEvidenceDomainView,
  AttemptObservabilityDomainView,
  BuiltinDomainView,
  BuiltinDomainViewKind,
  ClosedDomainEntry,
  DimensionSet,
  DomainViewQuery,
  DomainViewRequest,
  FileChangesDomainView,
  FrameQuery,
  MeasureSet,
  SandboxHistoryDomainView,
  SemanticFrame,
  SemanticRow,
  SourcesDomainView,
} from "./api.ts";

export type {
  AttemptEvidenceDomainDetail,
  AttemptObservabilityDomainDetail,
  BuiltinDomainDetail,
  ClosedBlobContent,
  ClosedCommandEntry,
  ClosedCommandInvocation,
  ClosedCommandOutcome,
  ClosedCommandStream,
  ClosedCommandWorkingDirectory,
  ClosedCommandsDetail,
  ClosedConversationDetail,
  ClosedConversationItem,
  ClosedConversationTurn,
  ClosedDiagnosticRedaction,
  ClosedDiagnosticsDetail,
  ClosedFileChange,
  ClosedFileChangeEndpoint,
  ClosedFileChangeWindow,
  ClosedFileChangesAttribution,
  ClosedFileChangesCollection,
  ClosedFileChangesCollectionLimitation,
  ClosedFileRevision,
  ClosedSourceFrame,
  ClosedTimingDetail,
  ClosedTimingInterval,
  ClosedTraceCollection,
  ClosedUsageDetail,
  ClosedUsageObservation,
  FileChangesDomainDetail,
  FileChangesNet,
  SourcesDomainDetail,
} from "./domain-view.ts";

export type {
  AcrossSlotsReduction,
  AnalysisDefinitionError,
  AnalysisInput,
  Denominator,
  Dimension,
  DimensionValue,
  EvidencePolicy,
  LogicalSlot,
  Measure,
  MeasureOptions,
  MissingPolicy,
  Population,
  PopulationMembers,
  ProducerPolicy,
  Relation,
  RelationTarget,
  WithinAttemptReduction,
  WithinSlotReduction,
} from "./definitions.ts";

export type {
  AnalysisCurrentSlotIdentity,
  AnalysisSlotOccurrenceIdentity,
  AnalysisRun,
  AnalysisRunContext,
  AnalysisRunExecution,
  AnalysisSelectionRequest,
  AnalysisSelectionSummary,
  EvalId,
  ExecutionIdentityDigest,
  AnalysisSlot,
  AnalysisIssue,
  AnalysisRequestError,
  SampleClosedError,
  SampleIdentity,
  AttemptId,
  ClosedRows,
  ClosedRowsIdentity,
  DomainView,
  EvidenceIdentity,
  EvidenceRef,
  ExperimentId,
  JsonValue,
  MeasureFormat,
  MetricBasis,
  MetricState,
  MetricValue,
  PopulationIdentity,
  ProducerIdentity,
  RunId,
  Sample,
  SampleCoverage,
  SampleSelector,
  SampleSnapshot,
  SampleSnapshotCodecError,
  SlotId,
} from "./contracts.ts";

export { ExperimentIdSchema } from "../record/codec/identifiers.ts";
