packages: []
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - niceeval@0.1.1
  - '@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-linux-x64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk-win32-x64@0.3.198'
  - '@anthropic-ai/claude-agent-sdk@0.3.198'
overrides:
  shell-quote: 1.9.0
  niceeval: link:../../../..
