import { dirname, join, resolve } from "node:path";
import { Data, Effect, Result, Schema } from "effect";
import { decodePayload, readRegistry, readRows, writeRegistry } from "../coordination/platform/sqlite-registries.ts";
import { hashEntryId } from "../shared/entry-file-store.ts";
import type { Verdict } from "../types.ts";
export interface KeptSandboxEntry { sandboxId:string; provider:string; evalId:string; attempt:number; experimentId?:string; locator:string; verdict:Verdict; keptAt:string; workdir:string; enter?:string; expiresAt?:string; state:"alive"|"dormant"|"expired"|"unknown" }
export interface KeptSandboxLease { holder:string; op:string; acquiredAt:string; ttlMs:number }
export class KeptSandboxRegistryError extends Data.TaggedError("KeptSandboxRegistryError")<{ readonly operation:string; readonly cause:unknown }>{}
export type KeptSandboxRegistryEffect<A> = Effect.Effect<A,KeptSandboxRegistryError>;
const Nonnegative=Schema.Number.pipe(Schema.check(Schema.makeFilter((n)=>Number.isSafeInteger(n)&&n>=0)));
const Timestamp=Schema.String.pipe(Schema.check(Schema.makeFilter((s)=>Number.isFinite(Date.parse(s)))));
const Entry=Schema.Struct({sandboxId:Schema.String,provider:Schema.String,evalId:Schema.String,attempt:Nonnegative,experimentId:Schema.optional(Schema.String),locator:Schema.String,verdict:Schema.Literals(["passed","failed","errored","skipped"]),keptAt:Timestamp,workdir:Schema.String,enter:Schema.optional(Schema.String),expiresAt:Schema.optional(Timestamp),state:Schema.Literals(["alive","dormant","expired","unknown"])});
const decode=(v:unknown):KeptSandboxEntry|undefined=>{const r=Schema.decodeUnknownResult(Entry)(v);return Result.isSuccess(r)?r.success:undefined};
const fail=(operation:string,cause:unknown)=>new KeptSandboxRegistryError({operation,cause});
const sync=<A>(operation:string,fn:()=>A):KeptSandboxRegistryEffect<A>=>Effect.try({try:fn,catch:(cause)=>fail(operation,cause)});
export function keptEntryId(provider:string,sandboxId:string):string{return hashEntryId([provider,sandboxId])}
export function sandboxesDirOf(root:string):string{return join(root,"sandboxes")}
export function findNiceevalRootEffect(cwd:string):KeptSandboxRegistryEffect<string|undefined>{return sync("find .niceeval directory",()=>{let current=resolve(cwd);for(;;){try{readRegistry(current.endsWith(".niceeval")?current:join(current,".niceeval"),()=>true);return current.endsWith(".niceeval")?current:join(current,".niceeval")}catch{}const parent=dirname(current);if(parent===current)return undefined;current=parent}})}
export function writeKeptEntryEffect(root:string,entry:KeptSandboxEntry):KeptSandboxRegistryEffect<void>{return sync("write kept sandbox entry",()=>writeRegistry(root,(db,encode)=>{db.prepare(`INSERT INTO kept_sandboxes(entry_id,provider,sandbox_id,kept_at,payload) VALUES(?,?,?,?,?) ON CONFLICT(entry_id) DO UPDATE SET kept_at=excluded.kept_at,payload=excluded.payload`).run(keptEntryId(entry.provider,entry.sandboxId),entry.provider,entry.sandboxId,entry.keptAt,encode(entry))}))}
export function readKeptEntriesEffect(root:string):KeptSandboxRegistryEffect<{entries:{id:string;entry:KeptSandboxEntry}[];malformed:string[]}>{return sync("read kept sandbox registry",()=>readRegistry(root,(db)=>{const entries:{id:string;entry:KeptSandboxEntry}[]=[];const malformed:string[]=[];for(const row of readRows(db,"SELECT entry_id,payload FROM kept_sandboxes ORDER BY kept_at,entry_id")){const entry=decode(decodePayload(row.payload));if(entry)entries.push({id:String(row.entry_id),entry});else malformed.push(String(row.entry_id))}return{entries,malformed}}))}
export function updateKeptEntryEffect(root:string,id:string,patch:Partial<KeptSandboxEntry>|((entry:KeptSandboxEntry)=>KeptSandboxEntry)):KeptSandboxRegistryEffect<boolean>{return sync("update kept sandbox entry",()=>writeRegistry(root,(db,encode)=>{const row=db.prepare("SELECT payload FROM kept_sandboxes WHERE entry_id=?").get(id) as {payload:unknown}|undefined;if(!row)return false;const current=decode(decodePayload(row.payload as never));if(!current)throw new Error("invalid kept sandbox metadata");const next=typeof patch==="function"?patch(current):{...current,...patch};db.prepare("UPDATE kept_sandboxes SET kept_at=?,payload=? WHERE entry_id=?").run(next.keptAt,encode(next),id);return true}))}
export function removeKeptEntryEffect(root:string,id:string):KeptSandboxRegistryEffect<void>{return sync("remove kept sandbox entry",()=>writeRegistry(root,(db)=>{db.prepare("DELETE FROM kept_sandboxes WHERE entry_id=?").run(id)}))}
export function readKeptLeaseEffect(root:string,id:string):KeptSandboxRegistryEffect<KeptSandboxLease|undefined>{return sync("read kept sandbox lease",()=>readRegistry(root,(db)=>{const r=db.prepare("SELECT holder,operation,acquired_at,ttl_ms FROM kept_sandbox_operation_leases WHERE entry_id=?").get(id) as Record<string,unknown>|undefined;return r?{holder:String(r.holder),op:String(r.operation),acquiredAt:String(r.acquired_at),ttlMs:Number(r.ttl_ms)}:undefined}))}
export function acquireKeptLeaseEffect(root:string,id:string,lease:KeptSandboxLease):KeptSandboxRegistryEffect<{acquired:true;token:string}|{acquired:false;lease:KeptSandboxLease}>{return sync("acquire kept sandbox lease",()=>writeRegistry(root,(db)=>{const row=db.prepare("SELECT generation,holder,operation,acquired_at,ttl_ms FROM kept_sandbox_operation_leases WHERE entry_id=?").get(id) as Record<string,unknown>|undefined;if(row&&Date.now()-Date.parse(String(row.acquired_at))<Number(row.ttl_ms))return{acquired:false as const,lease:{holder:String(row.holder),op:String(row.operation),acquiredAt:String(row.acquired_at),ttlMs:Number(row.ttl_ms)}};const generation=Number(row?.generation??0)+1;const token=`${id}:${generation}:${crypto.randomUUID()}`;db.prepare(`INSERT INTO kept_sandbox_operation_leases(entry_id,generation,token,holder,operation,acquired_at,ttl_ms) VALUES(?,?,?,?,?,?,?) ON CONFLICT(entry_id) DO UPDATE SET generation=excluded.generation,token=excluded.token,holder=excluded.holder,operation=excluded.operation,acquired_at=excluded.acquired_at,ttl_ms=excluded.ttl_ms`).run(id,generation,token,lease.holder,lease.op,lease.acquiredAt,lease.ttlMs);return{acquired:true as const,token}}))}
export function releaseKeptLeaseEffect(root:string,id:string,token:string):KeptSandboxRegistryEffect<void>{return sync("release kept sandbox lease",()=>writeRegistry(root,(db)=>{db.prepare("DELETE FROM kept_sandbox_operation_leases WHERE entry_id=? AND token=?").run(id,token)}))}
